baseurl: /champaign-urbana
permalink: pretty
markdown: kramdown
paginate: 5
repo: champaign-urbana
github_org: maptime
maptime:
  chapter: MaptimeCU
  twitter: MaptimeCU
  #disqus: YOUR DISQUS USERNAME
